import type { APIRoute } from "astro";

export const GET: APIRoute = () => {
  const body = [
    "# Piercova — Implant-Grade Body Piercing Jewelry",
    "",
    "> LLMs.txt — Structured context for AI crawlers, search engines, and LLM-based assistants.",
    "> Last updated: 2026-06-30",
    "",
    "## Brand Overview",
    "- Name: Piercova",
    "- Domain: https://www.piercova.com",
    "- Tagline: Implant-Grade Body Piercing Jewelry",
    "- Location: Yiwu, Zhejiang, China",
    "- Established: 2020",
    "- Target Market: United States, International",
    "- Email: support@piercova.com",
    "",
    "## Products & Categories",
    "- Earrings & Ear Piercing Jewelry: https://www.piercova.com/categories/earrings",
    "- Belly Rings (Navel Jewelry): https://www.piercova.com/categories/belly-rings",
    "- Nose Rings & Nostril Jewelry: https://www.piercova.com/categories/nose-rings",
    "- Lip Rings & Labret Studs: https://www.piercova.com/categories/lip-rings",
    "- Nipple Rings & Barbells: https://www.piercova.com/categories/nipple-rings",
    "",
    "## Materials",
    "- ASTM F136 Implant-Grade Titanium (Ti-6Al-4V ELI): https://www.piercova.com/materials/titanium",
    "  - Nickel-free, fully biocompatible, same alloy as surgical implants",
    "- ASTM F138 Implant-Grade 316LVM Surgical Steel: https://www.piercova.com/materials/surgical-steel",
    "  - Vacuum-melted, contains 12-14% nickel, not for nickel allergies",
    "- 925 Sterling Silver (ASTM B700): https://www.piercova.com/materials/sterling-silver",
    "  - 92.5% silver, nickel-free, healed piercings only",
    "- 14K Solid Gold (58.5% Au): https://www.piercova.com/materials/14k-gold",
    "  - Solid throughout, nickel-free options, luxury grade",
    "",
    "## Key Pages",
    "- About: https://www.piercova.com/about",
    "- FAQ: https://www.piercova.com/faq",
    "- Materials Guide: https://www.piercova.com/#materials",
    "",
    "## Shipping & Policies",
    "- Worldwide shipping from Yiwu, China",
    "- Standard international: 10-20 business days",
    "- Express (DHL/FedEx): 3-7 business days",
    "- Returns: Unopened items within 30 days (hygiene policy)",
    "",
    "## Technical",
    "- Built with: Astro 5 (Static Site Generation)",
    "- Hoster: Cloudflare Pages",
    "- Structured Data: JSON-LD (Organization, WebSite, FAQ, Product, BreadcrumbList)",
    "- Sitemap: https://www.piercova.com/sitemap-index.xml",
  ].join("\n");

  return new Response(body, {
    status: 200,
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
